Sub-hourly post-processing enabled by some new config.sh entries. Metatask entries added to the "run_post" task in the generated workflow.

diff --git a/jobs/JREGIONAL_RUN_POST b/jobs/JREGIONAL_RUN_POST
--- a/jobs/JREGIONAL_RUN_POST
+++ b/jobs/JREGIONAL_RUN_POST
@@ -88,7 +88,7 @@ else
 fi
 mkdir_vrfy -p "${postprd_dir}"
 
-fhr_dir="${postprd_dir}/$fhr"
+fhr_dir="${postprd_dir}/$fhr$fmin"
 check_for_preexist_dir_file "${fhr_dir}" "delete"
 mkdir_vrfy -p "${fhr_dir}"
 
@@ -108,6 +108,15 @@ digits:
   fhr = \"${fhr}\""
 fi
 #
+#-------------- check if all necessary environmental variables are included -----
+if [[ "${fmin}" ]] && [[ ! "${dt_atmos}" ]]; then
+  echo "ERROR: You set environmental variable \"fmin\" but did not supply \"dt_atmos\""
+  echo "  as well (same as in FV3 namelist). Both of these need to be set so that "
+  echo "  UPP will process the correct file for the first output timestep model fields."
+  exit 2
+fi
+#-------------------------------------------------------------------------
+#
 #-----------------------------------------------------------------------
 #
 # Call the ex-script for this J-job and pass to it the necessary varia-
@@ -120,7 +129,9 @@ $SCRIPTSDIR/exregional_run_post.sh \
   run_dir="${run_dir}" \
   postprd_dir="${postprd_dir}" \
   fhr_dir="${fhr_dir}" \
-  fhr="${fhr}" || \
+  fhr="${fhr}" \
+  fmin="${fmin}" \
+  dt_atmos="${dt_atmos}" || \
 print_err_msg_exit "\
 Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
 #
